---
title: "Seven Most Popular Cuisine type in New Yrok City"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(httr)
library(jsonlite)
```

```{r read data}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() 
```

```{r clean data}
nyc_new_data = nyc_inspections %>%
  janitor::clean_names() %>%
  select(cuisine_description,grade,score) %>%
  group_by(cuisine_description) %>%
  summarize(n_obs = n()) 
```

Column {data-width=500}
-----------------------------------------------------------------------
### Chart A
```{r}
nyc_most_popular = nyc_inspections %>%
  janitor::clean_names() %>%
  na.omit %>%
  filter(cuisine_description == "American" | cuisine_description == "Chinese" | cuisine_description == "Spanish" | cuisine_description == "Mexican" | cuisine_description == "Italian" | cuisine_description == "Japanese" | cuisine_description == "Caribbean") %>%
  select(cuisine_description,grade,score) 
nyc_most_popular %>%
  plot_ly( y = ~score, color = ~cuisine_description, type = "box",colors = "Set2") %>%
  layout(title = 'Score of seven most popular cuisine type')
```
Column {data-width=500}
-----------------------------------------------------------------------
### Chart B
```{r}
nyc_most_popular %>% 
  group_by(cuisine_description,grade) %>%
  summarize(n_obs = n()) %>%
  plot_ly(x=~grade , y=~n_obs , color= ~cuisine_description) %>%
layout(title = 'Counts of Grade by different cuisine type')

```

### Chart C
```{r}
nyc_most_popular %>%
  group_by(cuisine_description) %>%
  summarize(n_obs = n()) %>%
plot_ly(labels= ~cuisine_description, values= ~n_obs, type= 'pie' ) %>%
  layout(title = 'Seven Most Popular National Cuisine In NY City',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

